---
- name: "Listing parameters"
  debug:
    msg:
       - "operation                    : {{ operation }}"

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install rstudio 
  include_tasks: install.yml
  when: operation == 'install'

- name: Update rstudio 
  include_tasks: update.yml
  when: operation == 'update'

- name: revert-delete rstudio 
  include_tasks: delete.yml
  when: operation == 'delete'
